[package]
name = "roaster"
version = "0.1.0"
authors = ["Christian Schwarz <me@cschwarz.com>"]

[dependencies]
cortex-m = "0.1.4"
r0 = "0.1.0"

[dependencies.stm32f7_discovery]
path = "stm32f7-discovery"

[profile.release]
lto = true

